### ISSUE TITLE
Nov 2020 source data update

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#4] opened 2020-11-13 11:37 UTC
Latest data for ICA Members ICA

Can we update the dev server version of the data with this.

Note it has a .txt suffix because github complained about .csv suffix

[LOD export members 13 nov 2020.txt](https://github.com/SolidarityEconomyAssociation/ica-project/files/5536503/LOD.export.members.13.nov.2020.txt)

**Comment by wu-lee** [comment] 2020-11-13 17:06
That new ICA data rebuilt and deployed on https://dev.ica.solidarityeconomy.coop

**Comment by wu-lee** [comment] 2020-11-13 17:06
Suggestion: we create a place to store these data files, perhaps in a separate github repository for original data. We can then use the existing download mechanism which checks ETAG headers to trigger the rebuild when the data at the configured URL changes.

This would mean that data updates could be done by anyone who can post the file in the right place. The sausage factory would take care of the rest.

**Comment by ColmMassey** [comment] 2020-11-13 17:18
> That new ICA data rebuilt and deployed on https://dev.ica.solidarityeconomy.coop

So something has gone wrong with the Long/lats. Whadada ya know!

**Comment by ColmMassey** [comment] 2020-11-13 17:28
And we may have regression with how the data is displayed!

**Comment by ColmMassey** [comment] 2020-11-13 17:36
> 
> 
> And we may have regression with how the data is displayed!

Perhaps not. It was a html page caching issue combined with some field data missing for some new co-ops that have joined the ICA. Barbados Co-operative Business Association (BCBAL) has no Typology Set

**Comment by ColmMassey** [comment] 2020-11-13 17:41
> So something has gone wrong with the Long/lats. Whadada ya know!

I think it is becasue the column title for Longitude and latitude is now prefixed with "Main-"

**Comment by ColmMassey** [comment] 2020-11-13 17:42
> Suggestion: we create a place to store these data files, perhaps in a separate github repository for original data. We can then use the existing download mechanism which checks ETAG headers to trigger the rebuild when the data at the configured URL changes.

I like this. Can you create a ticket for it?

**Comment by ColmMassey** [comment] 2020-11-16 15:54
[LOD export members 16 nov 2020.txt](https://github.com/SolidarityEconomyAssociation/ica-project/files/5547405/LOD.export.members.16.nov.2020.txt)

Some fixes to the data.

**Comment by ColmMassey** [comment] 2020-11-16 15:57
Please update to use this one when fixing the Lo/lat issue.

**Comment by wu-lee** [comment] 2020-11-18 23:12
> I like this. Can you create a ticket for it?

I think you've done something like this in https://github.com/SolidarityEconomyAssociation/open-data/issues/58? Although for Nextcloud rather than Github. Added some answers there. Notably the ETAG seems to be missing so far, but need to check a shared CSV file.

IIRC Github does seem to support ETAGs on files in repositories.

**Comment by wu-lee** [comment] 2020-11-18 23:35
> > So something has gone wrong with the Long/lats. Whadada ya know!
> 
> I think it is becasue the column title for Longitude and latitude is now prefixed with "Main-"

That seems to be the case, but it is the case for the last three csv dumps, all the way back to 31st July, and including the latest one you've attached. I guess this is masked by geocoding filling in the location when the supplied ones are clobbered like this?

Isn't it a better solution to tell the ICA we can't work with their data unless they supply it in a consistent format? It doesn't seem sensible or fair to expect us to retroactively adapt our code to ad-hoc CSV heading changes, especially when they crop up unannounced.

**Comment by ColmMassey** [comment] 2020-11-19 10:14
> but it is the case for the last three csv dumps

So they have been consistent? No? so perhaps that is not the issue.

**Comment by ColmMassey** [comment] 2020-11-19 10:18
> I think you've done something like this in [SolidarityEconomyAssociation/open-data#58](https://github.com/SolidarityEconomyAssociation/open-data/issues/58)? Although for Nextcloud rather than Github. Added some answers there. Notably the ETAG seems to be missing so far, but need to check a shared CSV file.

Nextcloud option is a different case. Here I am exploring having someoen editiing a spreadsheet on NextCloud through a browser and have it then automatically rebuilt into a linked database. A distinct problem from using github.

**Comment by wu-lee** [comment] 2020-11-19 11:37
>  A distinct problem from using github.

Ok, then here's an issue: https://github.com/SolidarityEconomyAssociation/open-data/issues/59

**Comment by wu-lee** [comment] 2020-11-19 12:15
Headers in the last four ICA dumps are not totally consistent, but they all use `Main-` prefixes on many fields. `Main-Latitude` and `Main-Longitude` were added in the latter two. 

The converter script expects `Latitude` and `Longitude` currently, which suggests this has changed at some point since Dean implemented this.  I guess this means the converter script needs a review and some fixes.

However, it would be nice to have some assurance that these fields are going to remain as they are.  Do we have that?

```
==> ica-2020-07-21.csv <==
﻿"Contact ID","Organisation Name","Country","Super-region","Region","Main-Street Address","Main-Supplemental Address 1","Main-Supplemental Address 2","Main-City","Main-Postal Code","Website","Typology","Structure Type","Economic activity (primary)","Economic activities (additional)","Description for publications"

==> ica-2020-07-31.csv <==
﻿"Contact ID","Organisation Name","Country","Super-region","Region","Main-Street Address","Main-Supplemental Address 1","Main-Supplemental Address 2","Main-City","Main-Postal Code","Website","Typology","Structure Type","Economic activity (primary)","Economic activities (additional)","Description for publications"

==> ica-2020-11-13.csv <==
﻿"Contact ID","Organisation Name","Country","Super-region","Region","Main-Street Address","Main-Supplemental Address 1","Main-Supplemental Address 2","Main-City","Main-Postal Code","Main-Latitude","Main-Longitude","Website","Typology","Structure Type","Economic activity (primary)","Economic activities (additional)","Description for publications"

==> ica-2020-11-16.csv <==
﻿"Contact ID","Organisation Name","Country","Super-region","Region","Main-Street Address","Main-Supplemental Address 1","Main-Supplemental Address 2","Main-City","Main-Postal Code","Main-Latitude","Main-Longitude","Website","Typology","Structure Type","Economic activity (primary)","Economic activities (additional)","Description for publications"
```

**Comment by wu-lee** [comment] 2020-11-19 18:44
Ok, headers reviewed, I think it's just Latitude and Longitude which need adjusting, so I've adjusted and regenerated.

One case where there's a supplied lat/long is Norinchukin Bank:

**Comment by ColmMassey** [comment] 2020-11-19 21:09
Primary Activity seems to be missing from the Dialog now?!?!

**Comment by wu-lee** [comment] 2020-11-20 00:13
Checking dev-0 deployment, Norinchukin Bank specifically:
- Primary Activity seems to be in the static data... (see urls above)
- It isn't in the JSON in the browser
- It isn't in the SPARQL query results

Checking prod-0 deployment:
- Primary Activity seems to be in the static data... (see urls above)
- It is in the JSON in the browser
- It is in the SPARQL query results

However, the queries on prod-0 and dev-0 for the ica-project are essentially the same (the lod.coop URIs differ, that's all).

Hmm.

Aha: although the static data HTML table for Norinchukin has "Primary Activity: Financial Services", on dev-0 it *doesn't* have `essglobal:primarySector <https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/activities-ica/ICA140>` in the TTL, as prod-0 has.

The generated `standard.csv` has the value `Financial Services` (corresponding to ICA140 as per the TTL above).

At this point I suspect it's something to do with the vocab which seems specifically for the ICA in [activities-ica.skos][1]

Hunting for `activities-ica` in the `open-data` and working backwards... there's a flag `using_ica_activities` in a method related to the RDF generation, which is set by the sausage factory config parameter `USING_ICA_ACTIVITIES`.

And this isn't set in the `local.conf` file used in this case. This file is for local runs (like I'm doing) and isn't by design version controlled. Sigh. So I've just been caught out by a new parameter which needs to be set for the ICA config.

So, regenerated, redeployed to dev-0. And finally, the Primary Activity is there.

[1]: https://github.com/essglobal-linked-open-data/map-sse/blob/extension-test/vocabs/standard/activities-ica.skos

**Comment by ColmMassey** [comment] 2020-11-20 09:51
And now the dev version has reverted back to Open Street Map default. :-( Can you please enable the Thunderforest tiles?

**Comment by ColmMassey** [comment] 2020-11-20 09:56
>Can you please enable the Thunderforest tiles?

Or can that be overridden by a url parameter now?

**Comment by wu-lee** [comment] 2020-11-20 10:17
I confess I've never noticed Thunderforest tiles there, and I didn't think we could use them yet (because we didn't have an account until I created one yesterday?)

I don't know about URL parameters offhand, this must be something Dean implemented if it has been.  I've always tended to skim over issues which are assigned to him and focus on mine. The tiles being a case in point.  If you refer to an issue or something with background I can go and read up on this?

**Comment by ColmMassey** [comment] 2020-11-20 10:44
You shouldn't have needed to know the details of @dtmakm27 's Thunderforest work in order not to overwrite what he did. It seems to be a merge/version protocol issue.

**Comment by wu-lee** [comment] 2020-11-20 13:38
Poking around in sea-map's history, I can see Dean's added a `tileUrl` parameter. This would be settable in the `config.json` file or URL parameters. However, no sign of it in the `ica-project`'s `config.json`, so I would infer this means there's an URL parameter?

I don't know what the parameter should be set to, however...

**Comment by wu-lee** [comment] 2020-11-20 14:46
Ok, I can change the tiles with `tileUrl` in the `config.json` file, modulo a weird JSON parsing error if I don't escape the second forward-slash in the tile URL. Doesn't seem to be settable in the URL parameters when I try that.

Which tileset should I set it to @ColmMassey ? There's a list in the Thunderforest console: https://manage.thunderforest.com/dashboard

**Comment by wu-lee** [comment] 2020-11-20 14:54
Ok, no need to answer that if it is the Outdoor map as stated here: https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/236#issuecomment-717385553

Configured, committed, deployed to dev-0.

I checked: if Dean set this, it wasn't committed+pushed to GitHub.

**Comment by wu-lee** [comment] 2020-11-20 17:36
Set the attributions to refer to whichever map tile is used / or allow this to be set in config.

**Comment by ColmMassey** [comment] 2020-11-22 14:15
> or allow this to be set in config.

If choosing the config option, will the option to choose tile source be in same small file where attribution text is set?

**Comment by wu-lee** [comment] 2020-11-22 22:19
Currently going with the option of defining this in `config.json` so the same place that the tile source is.  Basically, because I can't see any simply way to infer the attribution text from the tile source URL, and `config.json` seems the obvious and simplest place to put it.

**Comment by wu-lee** [comment] 2020-11-22 22:33
So, attribution for Thunderforest now added on dev branch and deployed to dev-0

**Closed** 2020-11-23 11:35 UTC
